image: Visual Studio 2017

services:
  - mssql2017

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable -y

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.Storage.MsSql.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true 
  project: source/Jobbr.Storage.MsSql.sln

after_build:
  - cmd: nuget install ILMerge -ExcludeVersion -Version 2.14.1208
  - cmd: mkdir ilmerged
  - cmd: ILMerge\tools\ILMerge.exe /out:ilmerged/Jobbr.Storage.MsSql.dll source/Jobbr.Storage.MsSql/bin/Release/Jobbr.Storage.MsSql.dll /target:library /targetplatform:v4,C:\Windows\Microsoft.NET\Framework64\v4.0.30319 /wildcards /internalize:internalize_exclude.txt 
  - cmd: nuget pack source\Jobbr.Storage.MsSql.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Jobbr.Storage.MsSql.%GitVersion_SemVer%.nupkg"

deploy:
- provider: NuGet
  server: https://nuget.org
  api_key:
    secure: dmAor9/81YJtHhqccxBN1aHyDgLVB96KSqRlqnaiFxqF5ROMgz3jCivW8ROvv4N3
  on:
    appveyor_repo_tag: true