image: Visual Studio 2017

services:
  - mssql2017

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable --version 4.0.0

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.Storage.MsSql.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true 
  project: source/Jobbr.Storage.MsSql.sln

after_build:
  - cmd: nuget pack source\Jobbr.Storage.MsSql.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Jobbr.Storage.MsSql.%GitVersion_SemVer%.nupkg"

deploy:
- provider: NuGet
  server: https://nuget.org
  api_key:
    secure: dmAor9/81YJtHhqccxBN1aHyDgLVB96KSqRlqnaiFxqF5ROMgz3jCivW8ROvv4N3
  on:
    appveyor_repo_tag: true